### PR TITLE
[TASK] Ensure "typo3/cms-composer-installers" v5 compatibility

### LINKED ISSUE #403: Not compatible with typo3/cms-composer-installers v4.0.0-RC1
### What are you trying to achieve?

On a new TYPO3-11LTS-based site with typo3/testing-framework 6.1.6 and typo3/cms-composer-installers 4.0.0-rc1, I created some (dummy) unit tests for my site package and ran them using a copy of the TF-provided `UnitTests.xml`.

Running `vendor/bin/phpunit -c config/UnitTests.xml` (from within my DDEV-based container), I expect to get something like this:

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

...............................................................  63 / 744 (  8%)
............................................................... 126 / 744 ( 16%)
............................................................... 189 / 744 ( 25%)
............................................................... 252 / 744 ( 33%)
............................................................... 315 / 744 ( 42%)
............................................................... 378 / 744 ( 50%)
............................................................... 441 / 744 ( 59%)
............................................................... 504 / 744 ( 67%)
............................................................... 567 / 744 ( 76%)
............................................................... 630 / 744 ( 84%)
............................................................... 693 / 744 ( 93%)
...................................................             744 / 744 (100%)

Time: 00:00.537, Memory: 20.00 MB

OK (744 tests, 891 assertions)
```

(with fewer tests, of course, as I currently only have 1 dummy test to check that the setup works)

### What do you get instead?

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

Error in bootstrap script: Symfony\Component\Finder\Exception\DirectoryNotFoundException:
The "/var/www/html/public/typo3/sysext/*/" directory does not exist.
#0 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(350): Symfony\Component\Finder\Finder->in('/var/www/html/p...')
#1 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(255): TYPO3\CMS\Core\Package\PackageManager->scanPackagePathsForExtensions()
#2 /var/www/html/vendor/typo3/cms-core/Classes/Package/UnitTestPackageManager.php(31): TYPO3\CMS\Core\Package\PackageManager->scanAvailablePackages()
#3 /var/www/html/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(255): TYPO3\CMS\Core\Package\UnitTestPackageManager->initialize()
#4 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(71): TYPO3\CMS\Core\Core\Bootstrap::createPackageManager('TYPO3\\CMS\\Core\\...', Object(TYPO3\CMS\Core\Package\Cache\PackageStatesPackageCache))
#5 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(84): PHPUnit\Util\FileLoader::{closure}()
#6 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once('/var/www/html/v...')
#7 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/v...')
#8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(562): PHPUnit\Util\FileLoader::checkAndLoad('config/../vendo...')
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(344): PHPUnit\TextUI\Command->handleBootstrap('config/../vendo...')
#10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments(Array)
#11 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#12 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#13 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#14 {main}
```

### How to reproduce the issue?

Unfortunately, I cannot share my project (as it's a private customer project). Still, basically, it's something along the lines of:
1. create a new DDEV-based site installation from https://github.com/TYPO3/TYPO3.CMS.BaseDistribution
2. switch to typo3/cms-composer-installers v4.0.0-RC1
3. create and require a small (site) package that holds the tests
4. require the testing framework
5. write a dummy "hello world" unit test
6. run it

### Specify some data of the environment

- TYPO3 testing framework version: 6.16.6
- TYPO3 version: 11.5.16
- TYPO3 installation type: Composer within DDEV
- PHP version: 8.1.8
- Web server used + version: Apache 2.4.54
- Operating system: Linux

### PR DESCRIPTION
**Pull request by sbuerk**
Since TYPO3 v12.0 the "typo3/cms-composer-installers" package
is a hard requirement in version 5. This comes along with some
changes:

* system-extensions are no longer installed in
  `<public-dir>/typo3/sysext/*`

* extensions are no longer installed in
  `<public-dir>/typo3conf/ext/*`

Extension and System Extensions are now installed into the
`vendor-dir` folder, which is the default behaviour of the
composer package-manager. Generally, this is really good
move.

"typo3/testing-framework" expected a specific setup structure,
to provide correct symlinks for system and extensions for
functional- and acceptance test instances. Which is not given
anymore.

As a intermediate solution, a composer plugin has been put
into the wild, providing the the expected structure with
symlinks. Which is a horrable solution, but worked for the
meanwhile.

This change now introduces a testing-framework internal
composer package manager to retrieve informations about
root packags and required packages and use the loaded
information for symlink handling.

Benefits of the implementation:

* core- and test extensions to load can now be specified by
  using the extension-key and/or the composer package name.
  `typo3conf/ext/extension-key` compatibilty is added and
  works without changes. May be deprecated at a later point.

* absolute paths to test-fixture extensions still works the
  same way

* testing-framework do not longer expects system-extensions
  or extensions in a specific place

* works with cms-composer-installers 3, 4RC1 and 5 the same
  way

* "sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
  is obsolete now, therefore added a "replace" for it to
  `composer.json`

This restores working state. With further dedicated change, this
could be extended by adding a composer.json file scanner to find
and register `test-fixture extensions` directly. Which further
forces that extensions should have always a composer.json.

Releases: main, 7
Resolves: #403

--------------------------------------------------------------------------

tf-main (#434)

* [77624: [WIP][TASK] Test TF typo3/cms-composer-installers 5 changes](https://review.typo3.org/c/Packages/TYPO3.CMS/+/77624)
* [typo3/styleguide (PR)](https://github.com/TYPO3/styleguide/pull/373)

tf-7 (#435)

* [sbuerk/typo3-ensure-admin (PR)](https://github.com/sbuerk/typo3-ensure-admin/pull/6)
* [lolli42/dbdoctor (PR)](https://github.com/lolli42/dbdoctor/pull/26)

--------------------------------------------------------------------------

With this solution, unit-, functional and acceptance tests are working in
core, extension and project level without the need for further adjustments.

Minor adjustment in test invocation are needed, which are backwards compatible
for `typo3/cms-composer-installer 3.x / TYPO3 v11` without the need of the 
bridge plugin.

### CODE REVIEW

File: Classes/Composer/ComposerPackageManager.php [hunk 1]
```diff
@@ -0,0 +1,257 @@
...
+    public function getPackageInfo(string $name): ?PackageInfo
+    {
+        $name = $this->resolvePackageName($name);
+        return self::$packages[$name] ?? null;
+    }
+
+    /**
+     * Get list of system extensions keys. We need this as fallback if no core extensions are selected to be symlinked.
+     *
+     * @return string[]
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:56]:
```suggestion
     * @return list<string>
```

File: Classes/Composer/ComposerPackageManager.php [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+            rtrim(
+                $packageInfo->getRealPath() . '/' . ($packageInfo->getVendorDir() ?: 'vendor'),
+                '/'
+            )
+        );
+    }
+
+    /**
+     * TYPO3 Core Development Mono Repository has a special setup, where the system extension are not required by the
+     * root composer.json. Therefore, we need to look them up manually to add corresponding package information. This
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:127]:
```suggestion
     * root `composer.json`. Therefore, we need to look them up manually to add corresponding package information. This
```

File: Classes/Composer/ComposerPackageManager.php [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+     * allows us to handle system extensions in mono repository they same way as outside and make e.g. symlink system
+     * extensions to test instance simpler by eliminating the need for dedicated mono-repository handling there.
+     */
+    private function processMonoRepository(): void
+    {
+        if (! ($this->rootPackage()?->isMonoRepository() ?? false)) {
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:133]:
```suggestion
        if (!($this->rootPackage()?->isMonoRepository() ?? false)) {
```

File: Classes/Composer/ComposerPackageManager.php [hunk 4]
```diff
@@ -0,0 +1,257 @@
...
+
+    /**
+     * Adds the package information to the internal cache. Additionally, it sets the extensionKey to packageName
+     * map information, if a TYPO3 extension or system-extensions package information is handed over. This map
+     * is used to allow extensionKey or packageName for retrieving package information, which comes in handy to
+     * provide backward compatibility for test core- and test extension symlink configuration per test instance.
+     */
+    private function addPackageInfo(PackageInfo $packageInfo): void
+    {
+        if (self::$packages[$packageInfo->getName()] ?? null) {
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:191]:
```suggestion
        if (isset(self::$packages[$packageInfo->getName()])) {
```

File: Classes/Composer/ComposerPackageManager.php [hunk 5]
```diff
@@ -0,0 +1,257 @@
...
+        ) {
+            $name = basename($name);
+        }
+        return self::$extensionKeyToPackageNameMap[$name] ?? $name;
+    }
+
+    /**
+     * Get the sanitized package installation path.
+     *
+     * Note: Not using realpath() is done by intention. That gives us the ability, to eventually avoid duplicates and
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:232]:
```suggestion
     * Note: Not using `realpath()` is done by intention. That gives us the ability to eventually avoid duplicates and
```

Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:232]: Should this be "eventually" (i.e., in the end) or "potentially" (i.e., possibly)?

File: Classes/Composer/ComposerPackageManager.php [hunk 6]
```diff
@@ -0,0 +1,257 @@
...
+     *       act on both paths if needed.
+     */
+    private function getPackageInstallPath(string $name): string
+    {
+        return $this->sanitizePath((string)InstalledVersions::getInstallPath($name));
+    }
+
+    /**
+     * This method resolves relative path tokens directly ( e.g. '/../' ) and sanitizes the path from back-slash to
```
Comment (oliverklee) [inline Classes/Composer/ComposerPackageManager.php:241]:
```suggestion
     * This method resolves relative path tokens directly (e.g. `/../`) and sanitizes the path from backslash to
```

**Review by oliverklee — COMMENTED** [review]
One quick round of polish.
