### PR TITLE
[TASK] Ensure "typo3/cms-composer-installers" v5 compatibility

### LINKED ISSUE #403: Not compatible with typo3/cms-composer-installers v4.0.0-RC1
### What are you trying to achieve?

On a new TYPO3-11LTS-based site with typo3/testing-framework 6.1.6 and typo3/cms-composer-installers 4.0.0-rc1, I created some (dummy) unit tests for my site package and ran them using a copy of the TF-provided `UnitTests.xml`.

Running `vendor/bin/phpunit -c config/UnitTests.xml` (from within my DDEV-based container), I expect to get something like this:

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

...............................................................  63 / 744 (  8%)
............................................................... 126 / 744 ( 16%)
............................................................... 189 / 744 ( 25%)
............................................................... 252 / 744 ( 33%)
............................................................... 315 / 744 ( 42%)
............................................................... 378 / 744 ( 50%)
............................................................... 441 / 744 ( 59%)
............................................................... 504 / 744 ( 67%)
............................................................... 567 / 744 ( 76%)
............................................................... 630 / 744 ( 84%)
............................................................... 693 / 744 ( 93%)
...................................................             744 / 744 (100%)

Time: 00:00.537, Memory: 20.00 MB

OK (744 tests, 891 assertions)
```

(with fewer tests, of course, as I currently only have 1 dummy test to check that the setup works)

### What do you get instead?

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

Error in bootstrap script: Symfony\Component\Finder\Exception\DirectoryNotFoundException:
The "/var/www/html/public/typo3/sysext/*/" directory does not exist.
#0 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(350): Symfony\Component\Finder\Finder->in('/var/www/html/p...')
#1 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(255): TYPO3\CMS\Core\Package\PackageManager->scanPackagePathsForExtensions()
#2 /var/www/html/vendor/typo3/cms-core/Classes/Package/UnitTestPackageManager.php(31): TYPO3\CMS\Core\Package\PackageManager->scanAvailablePackages()
#3 /var/www/html/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(255): TYPO3\CMS\Core\Package\UnitTestPackageManager->initialize()
#4 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(71): TYPO3\CMS\Core\Core\Bootstrap::createPackageManager('TYPO3\\CMS\\Core\\...', Object(TYPO3\CMS\Core\Package\Cache\PackageStatesPackageCache))
#5 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(84): PHPUnit\Util\FileLoader::{closure}()
#6 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once('/var/www/html/v...')
#7 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/v...')
#8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(562): PHPUnit\Util\FileLoader::checkAndLoad('config/../vendo...')
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(344): PHPUnit\TextUI\Command->handleBootstrap('config/../vendo...')
#10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments(Array)
#11 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#12 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#13 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#14 {main}
```

### How to reproduce the issue?

Unfortunately, I cannot share my project (as it's a private customer project). Still, basically, it's something along the lines of:
1. create a new DDEV-based site installation from https://github.com/TYPO3/TYPO3.CMS.BaseDistribution
2. switch to typo3/cms-composer-installers v4.0.0-RC1
3. create and require a small (site) package that holds the tests
4. require the testing framework
5. write a dummy "hello world" unit test
6. run it

### Specify some data of the environment

- TYPO3 testing framework version: 6.16.6
- TYPO3 version: 11.5.16
- TYPO3 installation type: Composer within DDEV
- PHP version: 8.1.8
- Web server used + version: Apache 2.4.54
- Operating system: Linux

### PR DESCRIPTION
**Pull request by sbuerk**
Since TYPO3 v12.0 the "typo3/cms-composer-installers" package
is a hard requirement in version 5. This comes along with some
changes:

* system-extensions are no longer installed in
  `<public-dir>/typo3/sysext/*`

* extensions are no longer installed in
  `<public-dir>/typo3conf/ext/*`

Extension and System Extensions are now installed into the
`vendor-dir` folder, which is the default behaviour of the
composer package-manager. Generally, this is really good
move.

"typo3/testing-framework" expected a specific setup structure,
to provide correct symlinks for system and extensions for
functional- and acceptance test instances. Which is not given
anymore.

As a intermediate solution, a composer plugin has been put
into the wild, providing the the expected structure with
symlinks. Which is a horrable solution, but worked for the
meanwhile.

This change now introduces a testing-framework internal
composer package manager to retrieve informations about
root packags and required packages and use the loaded
information for symlink handling.

Benefits of the implementation:

* core- and test extensions to load can now be specified by
  using the extension-key and/or the composer package name.
  `typo3conf/ext/extension-key` compatibilty is added and
  works without changes. May be deprecated at a later point.

* absolute paths to test-fixture extensions still works the
  same way

* testing-framework do not longer expects system-extensions
  or extensions in a specific place

* works with cms-composer-installers 3, 4RC1 and 5 the same
  way

* "sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
  is obsolete now, therefore added a "replace" for it to
  `composer.json`

This restores working state. With further dedicated change, this
could be extended by adding a composer.json file scanner to find
and register `test-fixture extensions` directly. Which further
forces that extensions should have always a composer.json.

Releases: main, 7
Resolves: #403

--------------------------------------------------------------------------

tf-main (#434)

* [77624: [WIP][TASK] Test TF typo3/cms-composer-installers 5 changes](https://review.typo3.org/c/Packages/TYPO3.CMS/+/77624)
* [typo3/styleguide (PR)](https://github.com/TYPO3/styleguide/pull/373)

tf-7 (#435)

* [sbuerk/typo3-ensure-admin (PR)](https://github.com/sbuerk/typo3-ensure-admin/pull/6)
* [lolli42/dbdoctor (PR)](https://github.com/lolli42/dbdoctor/pull/26)

--------------------------------------------------------------------------

With this solution, unit-, functional and acceptance tests are working in
core, extension and project level without the need for further adjustments.

Minor adjustment in test invocation are needed, which are backwards compatible
for `typo3/cms-composer-installer 3.x / TYPO3 v11` without the need of the 
bridge plugin.

### CODE REVIEW

File: Classes/Core/Testbase.php [hunk 1]
```diff
@@ -249,9 +271,27 @@ public function setUpInstanceCoreLinks($instancePath): void
...
-    public function linkTestExtensionsToInstance($instancePath, array $extensionPaths): void
+    public function linkTestExtensionsToInstance(string $instancePath, array $extensionPaths): void
     {
         foreach ($extensionPaths as $extensionPath) {
+            $packageInfo = $this->composerPackageManager->getPackageInfo($extensionPath);
+            if ($packageInfo instanceof PackageInfo) {
+                $installPath = $packageInfo->getRealPath() . '/';
+                $destinationPath = $instancePath . '/typo3conf/ext/' . $packageInfo->getExtensionKey();
+                // @todo Need we some "relative" or "short-path" calculation for the symlink to avoid absolute source ?
+                $success = symlink($installPath, $destinationPath);
```
Comment (DavidBruchmann) [inline Classes/Core/Testbase.php:282]:
```suggestion
                $success = @symlink($installPath, $destinationPath);
```

File: Classes/Core/Testbase.php [hunk 2]
```diff
@@ -473,10 +514,11 @@ public function testDatabaseNameIsNotTooLong($originalDatabaseName, array $confi
...
-    public function setUpLocalConfiguration($instancePath, array $configuration, array $overruleConfiguration): void
+    public function setUpLocalConfiguration(string $instancePath, array $configuration, array $overruleConfiguration): void
     {
         // Base of final LocalConfiguration is core factory configuration
-        $finalConfigurationArray = require ORIGINAL_ROOT . 'typo3/sysext/core/Configuration/FactoryConfiguration.php';
+        $coreExtensionPath = $this->composerPackageManager->getPackageInfo('typo3/cms-core')->getRealPath();
+        $finalConfigurationArray = require $coreExtensionPath . '/Configuration/FactoryConfiguration.php';
         $finalConfigurationArray = array_replace_recursive($finalConfigurationArray, $configuration);
         $finalConfigurationArray = array_replace_recursive($finalConfigurationArray, $overruleConfiguration);
         $result = file_put_contents(
```
Comment (DavidBruchmann) [inline Classes/Core/Testbase.php:524]:
```suggestion
        $result = @file_put_contents(
```

File: Classes/Core/Testbase.php [hunk 3]
```diff
@@ -625,7 +677,7 @@ public function setUpBasicTypo3Bootstrap($instancePath): ContainerInterface
         // Reset state from a possible previous run
         GeneralUtility::purgeInstances();
 
-        $classLoader = require __DIR__ . '/../../../../autoload.php';
+        $classLoader = require $this->getPackagesPath() . '/autoload.php';
```
Comment (DavidBruchmann) [inline Classes/Core/Testbase.php:680]: even if naming of $classLoader is somehow reasonable, I don't like that it's used with the same meaning like $autoloadFile (line 240).  
About the assignment, perhaps a method is better than individual notation for each case?

File: Classes/Core/Testbase.php [hunk 4]
```diff
@@ -966,14 +1018,15 @@ protected function copyRecursive($from, $to)
...
+     * Since we are surly installed in the vendor dir, we can reuse the composer runtime information to get the
+     * correct installation path of the testing-framework. With that we can calculate the package folder precisely,
+     * avoiding invalid path determination when symlinks has been invited to the party.
      *
      * @return string Absolute path to vendor dir, without trailing slash
      */
     public function getPackagesPath(): string
     {
-        return rtrim(strtr(dirname(__DIR__, 4), '\\', '/'), '/');
+        return $this->composerPackageManager->getVendorPath();
```
Comment (DavidBruchmann) [inline Classes/Core/Testbase.php:1029]: like this this method is superfluous, isn't it?  
`$this->composerPackageManager->getVendorPath()` is more descriptive and clear anyway, imo.

**Review by DavidBruchmann — CHANGES_REQUESTED** [review]
It works so far with my test case.  
A few minor things I commented, which should perhaps be adjusted but at least you can have a look at it.

File: Classes/Core/Testbase.php (hunk 4 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php:1029]: We can deprecate it (later) or rename it, but IMO I would keep it because of compat reasons (see UnitBootstrap). That way, it works without being breaking.  For internal usage, we can directly use it from the composerPackageManager.

My overall goal was to keep needed changes for consumer as low as possible.

File: Classes/Core/Testbase.php (hunk 1 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php:282]: I thought I used the suppress for all new places after your recenently merged patch. Will check this again. Thanks.

File: Classes/Core/Testbase.php (hunk 2 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php:524]: Not sure if we should really suppress the file_put_contents() here. Anyway, could be a dedicated change. A change should only contain needed and related things and not starting to do a lot of unrelated side changes. But will have a detailed look later.

File: Classes/Core/Testbase.php (hunk 3 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php:680]: Same as above. The naming the same as before and unrelated to the goal of this change. Can be discussed and tackled in a dedicated change.

I want to stay on goal related stuff for this change (which is how we tend to work in the TYPO3 world). 

Anway, I would disagree with you here.

L680 requires the file and therefor the composer autoloader. L240 containts only the "path" to the autoload file, which is replaced in written files. Two different use-cases, and from my-side the naming are technical correct in both cases.

If you really want to discuss this, open a dedicated issue for this. This is absoluty unrelated to this change.

**Comment by DavidBruchmann** [comment]
there are still some minor issues in old code parts  like using the @ operator, but that can't be commented here and be done after the merge. It's not related to this PR.

File: Classes/Core/Testbase.php (hunk 2 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php]: Have added the silence-operator.

**Comment by sbuerk** [comment]
> there are still some minor issues in old code parts like using the @ operator, but that can't be commented here and be done after the merge. It's not related to this PR.

Please, stay away from commenting unrelated things on changes. You may be right, but please open a dedicated issue for this.

It's okay for new code introduced ... but not for lines not touched by the change. Otherwise we would never merge anything because we would find unrelated things in every change.

Does not mean I'm against it, but it's not helpfull to comment unrelated stuff on changes.

File: Classes/Core/Testbase.php (hunk 4 above)
Comment (DavidBruchmann) [reply Classes/Core/Testbase.php:1029]: ok, then just leave it for the moment.

File: Classes/Core/Testbase.php (hunk 1 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php]: Missed it in the backport. Fixed.

File: Classes/Core/Testbase.php (hunk 4 above)
Comment (sbuerk) [reply Classes/Core/Testbase.php:1029]: Would like to post-pone this to a dedicated change afterwards. And deciding if main only, or 7 to .. and if deprecation should be done or simply renaming.

Will discuss this with lolli. But postponing for now.

**Comment by sbuerk** [comment]
Beside this, please comment general things in the main change #434.

This is a pre-backport to test things with TF-7 in parallel.

**Review by lolli42 — APPROVED** [review]
